### PR TITLE
Peer2peer - Fix setLocalDescription parsing error when forceIsac is used

### LINKED ISSUE #86: Uncaught Error display when Forced iSAC  is used for the audio only in P2P call
1. On host A: Browse to peer2peer, fill in the Force iSAC checkbox, and call (audio only). 
2. On host B: Browse to peer2peer, fill in the Force iSAC checkbox, and call (audio only). 
3. Verify audio is flowing between the hosts. 

Expected Result: The audio should flow between the two users

Actual Result: The audio isn't flowing between the two users instead i see the error message as below:
Uncaught Error: setRemoteDescription

### PR DESCRIPTION
**Pull request by KaptenJansson**
fixes #86

### CODE REVIEW

**Comment by KaptenJansson** [comment]
I know the webcomponents and vulcanize changes in this Pull request are unrelated but they needed updating due to grunt complaining because travis pulls down the latest versions and 0.5.0 of webcomponentsjs were no longer available from NPM it seems and the one it pulled down, 0.6.2 breaks the dependancies due to not matching ^0.5.0.

File: src/manual/peer2peer/js/main.js [hunk 1]
```diff
@@ -1105,10 +1112,10 @@ function printHandler_(message, color) {
   }
   $('messages').innerHTML += '<span style="color:' + color + ';">' + message +
                             '</span><br>';
-  console.log(message);
   if (color === 'red') {
     throw new Error(message);
   }
+  console.log(message);
```
Comment (andresusanopinto) [inline src/manual/peer2peer/js/main.js]: nit: Why have you moved this line down? that way it will not be logged when actually throwing an error.

**Comment by andresusanopinto** [comment]
lgtm

File: src/manual/peer2peer/js/main.js (hunk 1 above)
Comment (KaptenJansson) [inline src/manual/peer2peer/js/main.js]: I moved it so that it does not print the message twice when errors occur. It will still be printed for non errors (i.e. color !== red)
