### PR TITLE
Fix WebAudio init handling

### LINKED ISSUE #267: Microphone not passing test
**Browsers and versions affected**
Chrome Version 66.0.3359.139 (Official Build) (64-bit)
Mac OSX 10.13.4 (17E202) High Sierra
Apple iMac MNE02LL/A 21.5 Inch, 3.4GHz Intel Core i5, 8GB RAM, 1TB Fusion Drive

**Steps to reproduce**
Browse to https://test.webrtc.org and click "START"

**Expected results**
Microphone should be activated and pass the microphone test.

**Actual results**
Site displays: 
[ OK ] Audio track created using device=Default - Built-in Microphone
[ FAILED ] No active input channels detected. Microphone is most likely muted or broken, please check if muted in the sound settings or physically on the device. Then rerun the test.

Console log shows:
The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page. https://goo.gl/7K7WLu
(anonymous) @ main.js:1

Note that the microphone works for all applications, and other sites such as this one: https://www.onlinemictest.com/

### PR DESCRIPTION
**Pull request by KaptenJansson**
**Description**
Update to use the new api for audioContext and move global audioContext creation to the mictest constructor.

Fixes #267, #261 

**Purpose**
Fix Mic input tests.

### CODE REVIEW

File: src/js/mictest.js [hunk 1]
```diff
@@ -44,16 +44,19 @@ function MicTest(test) {
...
   }
+  var AudioContext = window.AudioContext || window.webkitAudioContext;
+  this.audioContext = new AudioContext();
 }
 
 MicTest.prototype = {
   run: function() {
-    if (typeof audioContext === 'undefined') {
-      this.test.reportError('WebAudio is not supported, test cannot run.');
+    this.audioContext.resume().then(function() {
```
Comment (artita) [inline src/js/mictest.js]: nit: Why do we need `resume()` here?
Maybe it is worth adding a comment here.

Comment (KaptenJansson) [reply src/js/mictest.js]: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#webaudio TL;DR After the AudioContext has been created, it has to be resumed after a user has interacted with the page.

Comment (KaptenJansson) [reply src/js/mictest.js]: Added comment.
