### PR TITLE
Fix SDP mangling, fix reportFatal in call.js, use latest webrtc-adapter from NPM rather than bower

### LINKED ISSUE #178: bunch of "Uncaught (in promise)" JS errors in troubleshooter page
Steps to reproduce:
1. Open https://test.webrtc.org/ in Win 8 Chrome M50 Canary 50.0.2640.0
2. Click "Start" to run the tests 

Actual results:
Just when the "Throughput -> Video Bandwidth" tests start, I see a bunch of Uncaught (in promise) JS errors (as seen in screenshot below)

Link to report - https://test.webrtc.org/report/AMIfv96zztR8XR7FAqQe7HzA61mS0fg3qsizToalosh6RK3wQTmhMnaPwLw5LpOg7ezRcxf-S6qIcKJ6RqqHKHcPa60hpWaSRnNZ2pljocf3qxzHIC6Qm5qz8FFczXatJ7hW07c0cXJ9326ZzKTWWS4cclmDYu29vg

Logs attached
[testrtc-2016-02-04T23-04-12.705Z.log.zip](https://github.com/webrtc/testrtc/files/118409/testrtc-2016-02-04T23-04-12.705Z.log.zip)

uncaught in promise errors

### PR DESCRIPTION
**Pull request by KaptenJansson**
**Description**
* SDP has changed in Chrome M50 hence there are more video error correction params we need to remove for the bandwidth tests.
* Update and use latest webrtc-adapter from NPM rather than bower.
* Fix reportFatal (dead code) in call.js

Fixes #178 

**Purpose**
Fix errors seen in Chrome M50

### CODE REVIEW

**Comment by KaptenJansson** [comment]
Hold a sec realized the vulcanize was still pulling in the old adapter

**Comment by andresusanopinto** [comment]
This pull request does so much stuff at same time...

did we stop updating bower webrtc-adapter? why move to npm module?

File: src/js/camresolutionstest.js [hunk 1]
```diff
@@ -144,9 +144,9 @@ CamResolutionsTest.prototype = {
     video.setAttribute('muted', '');
     video.width = resolution[0];
     video.height = resolution[1];
-    attachMediaStream(video, stream);
+    video.srcObject = stream;
```
Comment (andresusanopinto) [inline src/js/camresolutionstest.js]: why didn't you have to use adapter.browserShim.atachMediaStream here?

File: src/manual/audio-and-video/index.html [hunk 2]
```diff
@@ -13,13 +13,12 @@
   <title>Single Local Preview (Video and Audio)</title>
   <meta http-equiv="X-UA-Compatible" content="chrome=1"/>
   <!-- Load the polyfill to switch-hit between Chrome and Firefox -->
-  <script src="../../../components/webrtc-adapter/adapter.js"></script>
+  <script src="../../../node_modules/webrtc-adapter/out/adapter.js"></script>
   <script type="text/javascript">
   function requestVideoAndAudio() {
     // Call into getUserMedia via the polyfill (adapter.js).
```
Comment (andresusanopinto) [inline src/manual/audio-and-video/index.html]: you can remove this comment now, right?

File: src/ui/gum-handler.html [hunk 3]
```diff
@@ -78,25 +80,23 @@
...
+        // directly.
+        for (var i = 0; i < stream.getVideoTracks().length; i++) {
+          stream.getVideoTracks()[i].stop();
+        }
+        for (var j = 0; j < stream.getAudioTracks().length; j++) {
+          stream.getAudioTracks()[j].stop();
+        }
+        this.pending = false;
+        this.error = false;
+      }.bind(this))
```
Comment (andresusanopinto) [inline src/ui/gum-handler.html]: This syntax looks weird:
 1 - not sure about indentation, I would expect .then/.catch to be indented as is common on fluent apis.
 2 - missing parenthesis around (function() {...})  before calling bind(). E:g. lalal(function() {}.bind(...)); looks very weird to me.

File: src/ui/testrtc-main.html [hunk 4]
```diff
@@ -171,29 +173,29 @@
...
         try {
           // Append the constraints with the getSource constraints.
           this.appendSourceId(this.$.audioSource.value, 'audio', constraints);
           this.appendSourceId(this.$.videoSource.value, 'video', constraints);
 
           traceGumEvent({'status': 'pending', 'constraints': constraints});
-          getUserMedia(constraints, successFunc, failFunc);
+          // Call into getUserMedia via the polyfill (adapter.js).
+          navigator.mediaDevices.getUserMedia(constraints)
+          .then(function(stream) {
```
Comment (andresusanopinto) [inline src/ui/testrtc-main.html]: again indentation looks weird.

Common at least for other languages is:

```
createBuilder()
    .setFoo(1234)
    .setBar(345)
    .build();
```

File: src/js/camresolutionstest.js (hunk 1 above)
Comment (KaptenJansson) [inline src/js/camresolutionstest.js]: Since it's deprecated, we should be able to use srcObject on Chrome and Firefox.

File: src/manual/audio-and-video/index.html (hunk 2 above)
Comment (KaptenJansson) [inline src/manual/audio-and-video/index.html]: Will do.

File: src/js/camresolutionstest.js (hunk 1 above)
Comment (andresusanopinto) [inline src/js/camresolutionstest.js]: Can you make all the calls of this project to attachMediaStream to go via the same mechanism.

Either all of them use: "video.srcObject = stream" or all of them use "adapter.browserShim.attachMediaStream(video, stream)".

Comment (KaptenJansson) [inline src/js/camresolutionstest.js]: That makes sense, fixed.

File: src/ui/gum-handler.html (hunk 3 above)
Comment (KaptenJansson) [inline src/ui/gum-handler.html]: 1. This is the style we have used everywhere in these repos. But I can change it here.
2. Nice catch!

File: src/ui/testrtc-main.html (hunk 4 above)
Comment (KaptenJansson) [inline src/ui/testrtc-main.html]: Fixed.

**Comment by KaptenJansson** [comment]
Sorry for doing so much in one PR, at least it's in separate commits.

**Comment by andresusanopinto** [comment]
lgtm
